pub fun erase(erase_arr, index){
    unsafe $unset {nameof erase_arr}[{index}]$
    unsafe ${nameof erase_arr}=("\$\{{nameof erase_arr}[@]}")$
    return erase_arr
}

// create an array of some specificied size and set all its elements to init
pub fun array(size, init) {
    let arr = [init] // sets arr to be the same type as init
    arr = erase(arr, 0) // immediately remove init in case size<=0

    loop _ in 0..size {arr += [init]}

    return arr
}